credentials:
  usernames:
    admin:
      email: jbquesnay@gmail.com
      name: Jean-Baptiste Quesnay
      password: $2b$12$.EOiu2qpB099PVJk0h1vyeyoFg11nwLFqLEGqI4DbawYXMfNJn.8e  # "admin123"
    jbquesnay:
      email: jbquesnay@gmail.com
      name: Jean-Baptiste Quesnay
      password: $2b$12$vR5toz/cafGRV7sdK7vqcudMCOpHo7JfSkWy3zJnB6Aql3oAACZVG  # "2ZZ9j$zp"

cookie:
  name: royce_rolls_dashboard
  key: royce_rolls_secret_key_2024_secure_random_string
  expiry_days: 30

